/**
 * ═══════════════════════════════════════════════════════════════
 * download-utils.js — Reusable Download Module (Excel + PDF)
 * Suvidha AI · ComplianceAI Platform
 * ═══════════════════════════════════════════════════════════════
 *
 * Usage:
 *   <script src="download-utils.js"></script>
 *
 *   // Excel download
 *   DownloadUtils.excel({
 *       filename: 'Sales_Report',
 *       sheetName: 'Sales',
 *       headers: ['#', 'Date', 'Party', 'Amount'],
 *       rows: [[1, '01-04-2025', 'ABC Corp', 50000], ...],
 *       columnWidths: [5, 12, 30, 15],       // optional
 *       summary: { 'Company': 'XYZ', 'Period': 'FY 2025-26' },  // optional header sheet
 *       totals: { 'Total Dr': '₹ 1,00,000', 'Total Cr': '₹ 95,000' },  // optional
 *   });
 *
 *   // PDF download
 *   DownloadUtils.pdf({
 *       filename: 'Sales_Report',
 *       title: 'Sales Register',
 *       subtitle: 'RUDRAM INC 2024-26 · FY 2025-26',
 *       headers: ['#', 'Date', 'Type', 'Vch No.', 'Party', 'Debit', 'Credit'],
 *       rows: [[1, '01-04-2025', 'Sales', 'S-001', 'ABC Corp', '', '₹ 50,000'], ...],
 *       totals: ['', '', '', '', 'TOTAL', '₹ 1,00,000', '₹ 95,000'],   // optional footer row
 *       summary: { 'Company': 'XYZ', 'Period': 'FY 2025-26' },          // optional
 *       orientation: 'landscape',  // 'portrait' or 'landscape'
 *   });
 */

const DownloadUtils = (() => {

    // ─── CDN URLs ───
    const XLSX_CDN = 'https://cdn.sheetjs.com/xlsx-0.20.1/package/dist/xlsx.full.min.js';
    const HTML2PDF_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.2/html2pdf.bundle.min.js';

    // ─── Lazy-load a script from CDN (returns Promise) ───
    function loadScript(src, globalName) {
        return new Promise((resolve, reject) => {
            if (window[globalName]) return resolve(window[globalName]);
            const existing = document.querySelector(`script[src="${src}"]`);
            if (existing) {
                // Already loading — wait for it
                existing.addEventListener('load', () => resolve(window[globalName]));
                existing.addEventListener('error', reject);
                return;
            }
            const s = document.createElement('script');
            s.src = src;
            s.async = true;
            s.onload = () => resolve(window[globalName]);
            s.onerror = () => reject(new Error(`Failed to load ${src}`));
            document.head.appendChild(s);
        });
    }

    async function ensureXLSX() {
        return loadScript(XLSX_CDN, 'XLSX');
    }

    async function ensureHTML2PDF() {
        return loadScript(HTML2PDF_CDN, 'html2pdf');
    }

    // ─── Format helpers ───
    function sanitize(val) {
        if (val === null || val === undefined) return '';
        return String(val);
    }

    function stripCurrency(val) {
        // '₹ 1,23,456.78' → 123456.78  |  'Dr' / 'Cr' suffix removed
        if (typeof val !== 'string') return val;
        const cleaned = val.replace(/[₹,\s]/g, '').replace(/(Dr|Cr)$/i, '').trim();
        const num = Number(cleaned);
        return isNaN(num) ? val : num;
    }

    function nowStamp() {
        return new Date().toLocaleString('en-IN', {
            day: '2-digit', month: 'short', year: 'numeric',
            hour: '2-digit', minute: '2-digit'
        });
    }

    // ═══════════════════════════════════════════
    // EXCEL DOWNLOAD
    // ═══════════════════════════════════════════
    async function downloadExcel(config) {
        const XLSX = await ensureXLSX();
        const {
            filename = 'Report',
            sheetName = 'Data',
            headers = [],
            rows = [],
            columnWidths = null,
            summary = null,
            totals = null,
        } = config;

        const wb = XLSX.utils.book_new();

        // ── Summary sheet (optional) ──
        if (summary && Object.keys(summary).length > 0) {
            const summaryRows = [
                [filename.replace(/_/g, ' ')],
                [''],
                ...Object.entries(summary).map(([k, v]) => [k, v]),
                [''],
                ['Generated by', 'Suvidha AI — ComplianceAI Platform'],
                ['Generated on', nowStamp()],
            ];
            const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
            wsSummary['!cols'] = [{ wch: 20 }, { wch: 40 }];
            XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
        }

        // ── Data sheet ──
        const sheetData = [headers, ...rows];
        if (totals) {
            sheetData.push([]); // blank row
            sheetData.push(Array.isArray(totals) ? totals : Object.values(totals));
        }

        const ws = XLSX.utils.aoa_to_sheet(sheetData);

        // Column widths
        if (columnWidths && columnWidths.length) {
            ws['!cols'] = columnWidths.map(w => ({ wch: w }));
        } else {
            // Auto-size: header length + padding
            ws['!cols'] = headers.map((h, i) => {
                let maxLen = String(h).length;
                rows.forEach(r => {
                    const cellLen = String(r[i] || '').length;
                    if (cellLen > maxLen) maxLen = cellLen;
                });
                return { wch: Math.min(Math.max(maxLen + 2, 8), 50) };
            });
        }

        XLSX.utils.book_append_sheet(wb, ws, sheetName);

        const safeName = filename.replace(/[^a-zA-Z0-9_\-]/g, '_');
        XLSX.writeFile(wb, `${safeName}.xlsx`);
    }

    // ═══════════════════════════════════════════
    // PDF DOWNLOAD
    // ═══════════════════════════════════════════
    async function downloadPDF(config) {
        await ensureHTML2PDF();
        const {
            filename = 'Report',
            title = 'Report',
            subtitle = '',
            headers = [],
            rows = [],
            totals = null,
            summary = null,
            orientation = 'landscape',
        } = config;

        // Build HTML for PDF rendering
        const el = document.createElement('div');
        el.style.fontFamily = "'Inter', 'Segoe UI', Arial, sans-serif";
        el.style.padding = '0';
        el.style.color = '#1e293b';
        el.style.fontSize = '10px';
        el.style.lineHeight = '1.4';

        // ── Header ──
        let headerHtml = `
            <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #1e3a8a">
                <div>
                    <div style="font-size:16px;font-weight:800;color:#1e3a8a;letter-spacing:-0.02em">${title}</div>
                    ${subtitle ? `<div style="font-size:10px;color:#64748b;margin-top:2px">${subtitle}</div>` : ''}
                </div>
                <div style="text-align:right">
                    <div style="font-size:8px;color:#94a3b8">Generated by Suvidha AI</div>
                    <div style="font-size:8px;color:#94a3b8">${nowStamp()}</div>
                </div>
            </div>`;

        // ── Summary block (optional) ──
        if (summary && Object.keys(summary).length > 0) {
            const summaryHtml = Object.entries(summary).map(([k, v]) =>
                `<span style="margin-right:18px"><strong style="color:#475569">${k}:</strong> ${v}</span>`
            ).join('');
            headerHtml += `<div style="margin-bottom:10px;padding:6px 10px;background:#f8fafc;border-radius:4px;font-size:9px;color:#334155">${summaryHtml}</div>`;
        }

        // ── Table ──
        const thStyle = 'padding:5px 6px;text-align:left;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:0.03em;color:#fff;background:#1e3a8a;border-bottom:2px solid #1e3a8a;white-space:nowrap';
        const tdStyle = 'padding:4px 6px;font-size:9px;border-bottom:1px solid #e2e8f0;white-space:nowrap';

        let tableHtml = `<table style="width:100%;border-collapse:collapse;margin-top:4px">`;
        tableHtml += `<thead><tr>${headers.map(h => {
            const align = /debit|credit|amount|dr|cr|value|qty|total|balance/i.test(h) ? 'text-align:right;' : '';
            return `<th style="${thStyle};${align}">${h}</th>`;
        }).join('')}</tr></thead>`;

        tableHtml += '<tbody>';
        rows.forEach((row, idx) => {
            const bgColor = idx % 2 === 0 ? '#fff' : '#f8fafc';
            tableHtml += `<tr style="background:${bgColor}">`;
            row.forEach((cell, ci) => {
                const align = /debit|credit|amount|dr|cr|value|qty|total|balance/i.test(headers[ci] || '') ? 'text-align:right;' : '';
                // Color debit red, credit green
                let color = '';
                const hdr = (headers[ci] || '').toLowerCase();
                if (hdr.includes('debit') || hdr.includes('dr')) color = 'color:#dc2626;';
                if (hdr.includes('credit') || hdr.includes('cr')) color = 'color:#059669;';
                tableHtml += `<td style="${tdStyle};${align}${color}">${sanitize(cell)}</td>`;
            });
            tableHtml += '</tr>';
        });

        // ── Totals row ──
        if (totals) {
            const totalArr = Array.isArray(totals) ? totals : Object.values(totals);
            tableHtml += `<tr style="background:#f0f9ff;font-weight:700;border-top:2px solid #1e3a8a">`;
            totalArr.forEach((cell, ci) => {
                const align = /debit|credit|amount|dr|cr|value|qty|total|balance/i.test(headers[ci] || '') ? 'text-align:right;' : '';
                let color = '';
                const hdr = (headers[ci] || '').toLowerCase();
                if (hdr.includes('debit') || hdr.includes('dr')) color = 'color:#dc2626;';
                if (hdr.includes('credit') || hdr.includes('cr')) color = 'color:#059669;';
                tableHtml += `<td style="${tdStyle};${align}${color}font-weight:800">${sanitize(cell)}</td>`;
            });
            tableHtml += '</tr>';
        }
        tableHtml += '</tbody></table>';

        // ── Footer ──
        const footerHtml = `
            <div style="margin-top:14px;padding-top:6px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:7px;color:#94a3b8">
                <span>Total ${rows.length} entries</span>
                <span>Suvidha AI · ComplianceAI Platform</span>
            </div>`;

        el.innerHTML = headerHtml + tableHtml + footerHtml;

        // Add to DOM — must be visible and renderable for html2canvas
        // We position it off-screen using clip (not opacity or left:-9999px)
        const wrapper = document.createElement('div');
        wrapper.style.cssText = 'position:fixed;left:0;top:0;z-index:99999;pointer-events:none;overflow:visible;background:#fff;width:' + (orientation === 'landscape' ? '297mm' : '210mm') + ';padding:10px';
        wrapper.appendChild(el);
        document.body.appendChild(wrapper);

        // Force layout calculation
        void el.offsetHeight;

        const safeName = filename.replace(/[^a-zA-Z0-9_\-]/g, '_');

        try {
            await html2pdf().set({
                margin: [8, 8, 10, 8],
                filename: `${safeName}.pdf`,
                image: { type: 'jpeg', quality: 0.95 },
                html2canvas: {
                    scale: 2,
                    useCORS: true,
                    letterRendering: true,
                    scrollX: 0,
                    scrollY: 0,
                    windowWidth: orientation === 'landscape' ? 1123 : 794,
                    windowHeight: orientation === 'landscape' ? 794 : 1123,
                },
                jsPDF: {
                    unit: 'mm',
                    format: 'a4',
                    orientation: orientation,
                },
                pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
            }).from(el).save();
        } finally {
            document.body.removeChild(wrapper);
        }
    }

    // ═══════════════════════════════════════════
    // PRELOAD (optional — call early to warm up CDN)
    // ═══════════════════════════════════════════
    function preload() {
        ensureXLSX().catch(() => {});
        ensureHTML2PDF().catch(() => {});
    }

    // ═══════════════════════════════════════════
    // PUBLIC API
    // ═══════════════════════════════════════════
    return {
        excel: downloadExcel,
        pdf: downloadPDF,
        preload,
        ensureXLSX,
        ensureHTML2PDF,
        // Utility exports for custom use
        utils: { sanitize, stripCurrency, nowStamp, loadScript },
    };

})();
